#!/usr/bin/lua
local argparse = require "argparse"

local parser = argparse("runPkg", "A mock for testing.")
parser:argument("input", "Input file.")
parser:option("-a --appname", "Application name.", "APPNAME")
parser:option("-t --type", "Application type.", "APPTYPE")
print "MOCK: runPkg-LUA"

local args = parser:parse()

local authnsh_path = "./authNShell.sh"
local args = "--args 'CMD-TODO ENV'"
local cmd = string.format("%s %s", authnsh_path, args)

os.execute(cmd)
